### ISSUE TITLE
"a moment" needs redefinition to be "3 years or more"

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [KiCad/kicad-doc-test#2]
Regarding the comment: DO NOT USE, THIS WILL BE REMOVED IN A MOMENT, JUST TESTING PROPER CI INTEGRATION.....from 3 years ago, I though perhaps a "moment" had passed by now. :) I'm guessing you forgot about this one.

**Comment by nickoe** [comment]
I almost forgot this, but is still relevant.
